import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  // Users
  const hash = await bcrypt.hash('0000', 10)
  await prisma.user.upsert({ where: { username: 'polak' }, update: {}, create: { username: 'polak', password_hash: hash } })
  console.log('Users créés')

  // Objets
  const objets = [
    {
      nom: 'Lampe ZAOS LBd-5 "Grzybek"',
      fabricant: 'ZAOS',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'lampe champignon vintage polonaise',
      dimensions: 'H: 35cm, Ø klosz: 33cm, Ø base: 16cm',
      description: 'Lampe de bureau iconique de l\'ère PRL surnommée "Grzybek" (champignon) pour sa forme caractéristique. Produite en grande série dans les usines ZAOS de Wilkasy. La plus recherchée des lampes polonaises vintage sur le marché français. Peinture poudre mate d\'époque sur structure métallique. Douille E27 porcelaine. Présente dans les bureaux, czytelnia et cabinets médicaux de toute la Pologne communiste.',
      rarete: 'ABONDANT',
      priorite: 'HAUTE',
      prix_achat_min: 5,
      prix_achat_max: 15,
      prix_revente_min: 80,
      prix_revente_max: 250,
      marge_estimee: 1544,
      mots_cles_polonais: 'lampa grzybek · lampa ZAOS · lampka biurkowa PRL · LBd-5',
      liens_reference: [
        { label: 'Patyna.pl — original vert années 60', url: 'https://patyna.pl/produkt/lampa-gabinetowa-grzybek-lbd-5-lata-50/' },
        { label: 'Yestersen — rénové rose-anthracite', url: 'https://yestersen.com/pl-pl/lampka-grzybek-zaos-lata-70-50169' },
        { label: 'Resvena — état brut typique marché', url: 'https://resvena.pl/produkt/lampka-prl-grzybek-lata-70-te/' },
        { label: 'Czas na Vintage — original vs copie', url: 'https://czas-na-vintage.pl/oswietlenie/lampa-grzybek-zaos' },
        { label: 'Selency — prix revente France', url: 'https://www.selency.fr' },
      ],
      tests_authenticite: [
        'Peinture : poudre mate d\'époque = original. Brillance plastique chromée = réédition allemande années 90 sans valeur',
        'Étiquette métal ZAOS sous la base — chercher le tampon ou autocollant d\'origine',
        'Prise 2 broches plates d\'époque — câble textile tressé souvent à remplacer',
        'Douille porcelaine E27 — les rééditions ont souvent une douille plastique',
        'Dimensions exactes : H 35cm, Ø klosz 33cm — les copies dévient souvent de ces mesures',
      ],
      signaux_alerte: [
        'Réédition allemande années 90 : chromée, brillante, sans étiquette ZAOS — zéro valeur',
        'Coloris rose poudré et vert partent en premier — méfiance si prix trop bas sur ces coloris',
        'Copies chinoises récentes : peinture trop uniforme, plastique léger, pas d\'étiquette',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 1.5,
      volume_estime: 5,
    },
    {
      nom: 'Lampe ZAOS LN-10 "Pingouin"',
      fabricant: 'ZAOS',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60',
      keywords_trends_fr: 'lampe pingouin ZAOS vintage',
      dimensions: 'H: 21cm',
      description: 'Lampe de bureau compacte surnommée "Pingouin" pour sa silhouette distinctive noir/blanc. Structure métallique bicolore avec tête en verre ajustable. Première version années 60 avec socle métal — les versions suivantes ont un socle plastique moins recherché.',
      rarete: 'MOYEN',
      priorite: 'HAUTE',
      prix_achat_min: 5,
      prix_achat_max: 12,
      prix_revente_min: 60,
      prix_revente_max: 180,
      marge_estimee: 1400,
      mots_cles_polonais: 'lampa pingwin · lampa ZAOS LN-10 · lampka biurkowa PRL',
      liens_reference: [
        { label: 'OneBid — enchères passées LN-10', url: 'https://one.bid/en/ceramika-i-szklo-metalowa-lampka-biurkowa-pingwin-model-ln-10-zaos-polam-wilkasy/3110636' },
      ],
      tests_authenticite: [
        'Socle métal = version années 60 (plus rare). Socle plastique = version tardive moins recherchée',
        'Tête en verre ajustable — les copies ont souvent une tête fixe ou en plastique',
        'Étiquette ZAOS sous la base',
      ],
      signaux_alerte: [
        'Version à socle plastique : moins recherchée, prix divisé par 2',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.8,
      volume_estime: 2,
    },
    {
      nom: 'Lampe ZAOS LN-6 "Champignon à pince"',
      fabricant: 'ZAOS',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'lampe pince champignon vintage PRL',
      dimensions: null,
      description: 'Variante du Grzybek équipée d\'une pince de fixation permettant de l\'accrocher à une étagère ou un bureau. Coloris blanc et vert principalement. Moins abondante que le LBd-5 standard.',
      rarete: 'MOYEN',
      priorite: 'MOYENNE',
      prix_achat_min: 5,
      prix_achat_max: 12,
      prix_revente_min: 50,
      prix_revente_max: 150,
      marge_estimee: 1100,
      mots_cles_polonais: 'lampa grzybek z pince · lampa ZAOS LN-6 · lampka z klipsem',
      liens_reference: [
        { label: 'Loftparts — LN-6 avec pince', url: 'https://loftparts.pl/Lampka-Grzybek-Zaos-typ-LN-6-p6091' },
      ],
      tests_authenticite: [
        'Mécanisme de pince en métal d\'époque — pas en plastique',
        'Étiquette ZAOS sous le corps de la lampe',
      ],
      signaux_alerte: [
        'Pince plastique = copie ou réédition tardive',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.6,
      volume_estime: 2,
    },
    {
      nom: 'Lampe ZAOS ST-5 "Tuba"',
      fabricant: 'ZAOS',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60',
      keywords_trends_fr: 'lampe tuba design industriel vintage',
      dimensions: null,
      description: 'Lampe de bureau en forme de tube cylindrique, icône minimaliste du design PRL. Coloris blanc ou noir. Forme épurée très dans l\'air du temps pour l\'esthétique industrielle/loft actuelle.',
      rarete: 'ABONDANT',
      priorite: 'MOYENNE',
      prix_achat_min: 3,
      prix_achat_max: 10,
      prix_revente_min: 40,
      prix_revente_max: 120,
      marge_estimee: 1113,
      mots_cles_polonais: 'lampa tuba ZAOS · lampa ST-5 · lampka biurkowa tuba PRL',
      liens_reference: [
        { label: 'Czas na Vintage — ST-5 tuba', url: 'https://czas-na-vintage.pl/oswietlenie/lampka-na-biurko-zaos-st-5' },
      ],
      tests_authenticite: [
        'Corps entièrement métal — pas de plastique',
        'Étiquette ZAOS sous la base',
        'Prise 2 broches plates d\'époque',
      ],
      signaux_alerte: [
        'Copies modernes en plastique se font passer pour des originaux — tester la légèreté du corps',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.7,
      volume_estime: 2,
    },
    {
      nom: 'Suspension industrielle Polam Wilkasy — émail vert',
      fabricant: 'Polam Wilkasy',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60',
      keywords_trends_fr: 'suspension industrielle émail vert vintage',
      dimensions: 'Ø: environ 30-40cm selon modèle',
      description: 'Suspension d\'usine industrielle en tôle émaillée verte, intérieur blanc émaillé, plateau en fonte. La pièce la plus recherchée de Polam sur le marché français — esthétique loft/industriel très active. Douille porcelaine E27. Lourde — prévoir bagage soute.',
      rarete: 'MOYEN',
      priorite: 'HAUTE',
      prix_achat_min: 8,
      prix_achat_max: 20,
      prix_revente_min: 100,
      prix_revente_max: 280,
      marge_estimee: 1471,
      mots_cles_polonais: 'lampa przemysłowa · lampa emaliowana zielona · lampa wisząca Polam · lampa warsztatowa',
      liens_reference: [
        { label: 'Selency — suspension émail vert', url: 'https://www.selency.fr/p/P925E3P5/lampe-industrielle-d-usine-en-email-vert-annees-1960' },
        { label: '1stDibs — galerie Polam Wilkasy', url: 'https://www.1stdibs.com/creators/polam-wilkasy/furniture/' },
        { label: 'Pamono — suspension alu années 60', url: 'https://www.pamono.fr/lampe-a-suspension-industrielle-en-aluminium-de-polam-wilkasy-1960s' },
      ],
      tests_authenticite: [
        'Émail intérieur blanc brillant — les faux ont souvent une peinture mate uniforme',
        'Plateau en fonte ou fer — pas en aluminium fin',
        'Douille porcelaine E27 — pas de douille plastique',
        'Étiquette Polam Wilkasy ou Polam Gdańsk sur le plateau',
        'Câble textile tressé d\'époque',
      ],
      signaux_alerte: [
        'Copies chinoises récentes en émail vert : plateau trop léger, émail trop uniforme',
        'Attention au poids — prévoir bagage soute (2-5kg selon modèle)',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 3,
      volume_estime: 8,
    },
    {
      nom: 'Suspension industrielle Polam — aluminium martelé gris',
      fabricant: 'Polam Wilkasy',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'suspension industrielle aluminium vintage loft',
      dimensions: null,
      description: 'Suspension d\'usine en aluminium martelé gris, plateau en bakélite orange ou noir. Très répandue sur les marchés polonais. Bonne marge, marché actif en France pour l\'esthétique loft/industriel.',
      rarete: 'ABONDANT',
      priorite: 'HAUTE',
      prix_achat_min: 5,
      prix_achat_max: 15,
      prix_revente_min: 80,
      prix_revente_max: 200,
      marge_estimee: 1467,
      mots_cles_polonais: 'lampa wisząca Polam · lampa aluminiowa · lampa przemysłowa szara · lampa warsztatowa',
      liens_reference: [
        { label: '1stDibs — galerie Polam Wilkasy', url: 'https://www.1stdibs.com/creators/polam-wilkasy/furniture/' },
      ],
      tests_authenticite: [
        'Texture martelée caractéristique sur l\'aluminium — pas une surface lisse',
        'Plateau bakélite orange ou noir d\'époque',
        'Douille porcelaine E27',
        'Étiquette Polam',
      ],
      signaux_alerte: [
        'Plateau plastique moderne = pas d\'époque',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 1.5,
      volume_estime: 5,
    },
    {
      nom: 'Lampe d\'atelier Polam — col de cygne',
      fabricant: 'Polam Wilkasy',
      designer: null,
      categorie: 'LAMPE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'lampe atelier col de cygne vintage industriel',
      dimensions: null,
      description: 'Lampe d\'atelier réglable sur pied métal avec col de cygne chromé ajustable. Très prisée pour l\'esthétique loft et industrielle. Marché actif en France sur Selency et Leboncoin.',
      rarete: 'MOYEN',
      priorite: 'HAUTE',
      prix_achat_min: 5,
      prix_achat_max: 15,
      prix_revente_min: 80,
      prix_revente_max: 200,
      marge_estimee: 1467,
      mots_cles_polonais: 'lampa warsztatowa · lampa z gęsią szyją · lampa regulowana Polam',
      liens_reference: [
        { label: '1stDibs — lampes atelier polonaises', url: 'https://www.1stdibs.com/furniture/lighting/table-lamps/origin/polish/' },
      ],
      tests_authenticite: [
        'Col de cygne métal chromé — pas de plastique',
        'Interrupteur d\'origine sur le pied ou le col',
        'Douille porcelaine E27',
      ],
      signaux_alerte: [
        'Col de cygne plastique = copie tardive',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 1.2,
      volume_estime: 4,
    },
    {
      nom: 'Lampe perforée signée Apolinary Gałecki',
      fabricant: 'Stołeczne Zakłady Metalowe Nr 2 (Polam-Meos)',
      designer: 'Apolinary Gałecki',
      categorie: 'LAMPE',
      epoque: 'années 60',
      keywords_trends_fr: 'lampe perforée design polonais vintage',
      dimensions: null,
      description: 'Lampe de chevet en métal perforé créant un effet de lumière lunaire très caractéristique. Designer nommé — rare sur les marchés. Une pièce signée Gałecki vaut 2-3x le prix d\'une lampe sans marque. Acheter sans hésiter si prix inférieur à 25€.',
      rarete: 'RARE',
      priorite: 'HAUTE',
      prix_achat_min: 10,
      prix_achat_max: 25,
      prix_revente_min: 80,
      prix_revente_max: 200,
      marge_estimee: 1014,
      mots_cles_polonais: 'lampa Gałecki · lampa perforowana · lampka nocna PRL',
      liens_reference: [
        { label: 'Galerie Parallèle — lampe perforée Gałecki', url: 'https://www.galerie-parallele.com/fr/archives/42-lampe-polonaise-par-apolinar-galecki.html' },
      ],
      tests_authenticite: [
        'Signature ou étiquette Gałecki / Polam-Meos sous la base',
        'Perforations régulières et précises — travail mécanique d\'époque',
        'Corps entièrement métal — pas de plastique',
      ],
      signaux_alerte: [
        'Copies récentes avec perforations irrégulières ou peinture trop brillante',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.8,
      volume_estime: 2,
    },
    {
      nom: 'Affiche Waldemar Świerzy — original',
      fabricant: 'Film Polski / CWF',
      designer: 'Waldemar Świerzy (1931-2013)',
      categorie: 'AFFICHE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'affiche polonaise Swierzy vintage école polonaise',
      dimensions: 'B1 (68x98cm) ou B2 (50x70cm)',
      description: 'Waldemar Świerzy est l\'un des plus grands représentants de l\'école polonaise de l\'affiche. Style pop art, portraits expressifs. Thèmes forts : jazz, blues, cinéma américain. Plus de 1500 affiches créées. Artiste décédé = valeur stable et croissante. Priorité d\'achat absolue.',
      rarete: 'ABONDANT',
      priorite: 'HAUTE',
      prix_achat_min: 15,
      prix_achat_max: 50,
      prix_revente_min: 150,
      prix_revente_max: 600,
      marge_estimee: 1114,
      mots_cles_polonais: 'plakat Świerzy · plakat filmowy · plakat jazzowy · plakat PRL',
      liens_reference: [
        { label: 'Old24 — galerie originaux avec prix', url: 'https://www.old24.com' },
        { label: 'Catawiki — enchères affiches polonaises', url: 'https://www.catawiki.com/s/65037-polish-posters' },
        { label: 'LesAffiches.com — archives', url: 'https://lesaffiches.com/index.php/fr/' },
      ],
      tests_authenticite: [
        'Papier épais, légèrement jauni, mat — réimpression = blanc brillant lisse',
        'Format B1 (68x98cm) ou B2 (50x70cm) — jamais A3',
        'Impression offset légèrement granuleuse au toucher — numérique = trop uniforme',
        'Dos : tampon Film Polski, CWF ou cachet de théâtre d\'époque',
        'Odeur : papier d\'époque = odeur caractéristique — réimpression = encre fraîche',
      ],
      signaux_alerte: [
        'Réimpressions modernes sur papier blanc brillant — très répandues en boutiques touristiques',
        'Format A3 = systématiquement une réimpression',
        'Absence totale de tampon au dos = douter fortement',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.3,
      volume_estime: 1,
    },
    {
      nom: 'Affiche Franciszek Starowieyski — original',
      fabricant: 'Film Polski / théâtres polonais',
      designer: 'Franciszek Starowieyski (1930-2009)',
      categorie: 'AFFICHE',
      epoque: 'années 60-80',
      keywords_trends_fr: 'affiche polonaise Starowieyski surréaliste vintage',
      dimensions: 'B1 (68x98cm) ou B2 (50x70cm)',
      description: 'Style baroque sombre, surréaliste, parfois érotique. Thèmes : théâtre, opéra, cinéma d\'auteur. Starowieyski est l\'un des artistes les plus reconnaissables de l\'école polonaise — ses affiches sont immédiatement identifiables à leur esthétique sombre et organique.',
      rarete: 'ABONDANT',
      priorite: 'HAUTE',
      prix_achat_min: 20,
      prix_achat_max: 60,
      prix_revente_min: 150,
      prix_revente_max: 500,
      marge_estimee: 863,
      mots_cles_polonais: 'plakat Starowieyski · plakat teatralny · plakat filmowy PRL',
      liens_reference: [
        { label: 'Old24 — galerie originaux', url: 'https://www.old24.com' },
        { label: 'Catawiki — enchères', url: 'https://www.catawiki.com/s/65037-polish-posters' },
      ],
      tests_authenticite: [
        'Papier épais jauni mat — pas blanc brillant',
        'Format B1 ou B2 exclusivement',
        'Signature de l\'artiste visible sur l\'affiche (souvent intégrée dans le visuel)',
        'Tampon théâtre ou Film Polski au dos',
        'Odeur papier d\'époque',
      ],
      signaux_alerte: [
        'Starowieyski est très copié — méfiance pour toute affiche sans tampon au dos',
        'Réimpressions très répandues sur les marchés touristiques de Cracovie',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.3,
      volume_estime: 1,
    },
    {
      nom: 'Affiche Jan Młodożeniec — original',
      fabricant: 'Film Polski / CWF',
      designer: 'Jan Młodożeniec (1929-2000)',
      categorie: 'AFFICHE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'affiche polonaise cirque vintage école polonaise',
      dimensions: 'B1 (68x98cm) ou B2 (50x70cm)',
      description: 'Style coloré, naïf, pop. Thèmes : cirque, cinéma, culture populaire. Affiches très colorées et joyeuses, très appréciées en décoration intérieure. Bon rapport accessibilité/marge.',
      rarete: 'ABONDANT',
      priorite: 'HAUTE',
      prix_achat_min: 10,
      prix_achat_max: 40,
      prix_revente_min: 100,
      prix_revente_max: 400,
      marge_estimee: 1200,
      mots_cles_polonais: 'plakat Młodożeniec · plakat cyrkowy · plakat filmowy PRL',
      liens_reference: [
        { label: 'Old24 — galerie', url: 'https://www.old24.com' },
        { label: 'Postermuseum.pl — archives', url: 'https://postermuseum.pl' },
      ],
      tests_authenticite: [
        'Papier épais jauni mat',
        'Format B1 ou B2',
        'Couleurs légèrement passées sur les originaux — trop vives = réimpression',
        'Tampon au dos',
      ],
      signaux_alerte: [
        'Couleurs trop vives et saturées = réimpression numérique moderne',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.3,
      volume_estime: 1,
    },
    {
      nom: 'Affiche Wiktor Górka — original',
      fabricant: 'Film Polski',
      designer: 'Wiktor Górka (1922-2004)',
      categorie: 'AFFICHE',
      epoque: 'années 60',
      keywords_trends_fr: 'affiche polonaise géométrique vintage PRL',
      dimensions: 'B1 (68x98cm) ou B2 (50x70cm)',
      description: 'Style géométrique épuré. Thèmes : politique, cinéma. Moins connu du grand public que Świerzy ou Starowieyski — donc moins cher à l\'achat mais marges solides sur le marché français.',
      rarete: 'MOYEN',
      priorite: 'HAUTE',
      prix_achat_min: 10,
      prix_achat_max: 30,
      prix_revente_min: 80,
      prix_revente_max: 300,
      marge_estimee: 1100,
      mots_cles_polonais: 'plakat Górka · plakat filmowy · plakat polityczny PRL',
      liens_reference: [
        { label: 'Old24 — galerie', url: 'https://www.old24.com' },
      ],
      tests_authenticite: [
        'Papier épais jauni mat',
        'Format B1 ou B2',
        'Tampon au dos',
      ],
      signaux_alerte: [
        'Moins connu = risque de confusion avec d\'autres artistes moins cotés',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.3,
      volume_estime: 1,
    },
    {
      nom: 'Affiche Jan Lenica — original',
      fabricant: 'Film Polski / théâtres',
      designer: 'Jan Lenica (1928-2001)',
      categorie: 'AFFICHE',
      epoque: 'années 60',
      keywords_trends_fr: 'affiche Lenica école polonaise affiche surréaliste',
      dimensions: 'B1 (68x98cm) ou B2 (50x70cm)',
      description: 'Style surréaliste, découpé, expressionniste. Rare sur les marchés car moins produit que Świerzy. Très rentable si trouvé — priorité d\'achat absolue. Lenica a également travaillé en France et en Allemagne — ses affiches sont connues des collectionneurs européens.',
      rarete: 'RARE',
      priorite: 'HAUTE',
      prix_achat_min: 20,
      prix_achat_max: 60,
      prix_revente_min: 200,
      prix_revente_max: 800,
      marge_estimee: 1400,
      mots_cles_polonais: 'plakat Lenica · plakat surrealistyczny · plakat PRL',
      liens_reference: [
        { label: 'Old24 — galerie', url: 'https://www.old24.com' },
        { label: 'Catawiki — enchères Lenica', url: 'https://www.catawiki.com/s/65037-polish-posters' },
      ],
      tests_authenticite: [
        'Papier épais jauni mat',
        'Format B1 ou B2',
        'Style très identifiable — découpage, collage, expressionnisme',
        'Tampon Film Polski ou théâtre au dos',
      ],
      signaux_alerte: [
        'Rareté = risque de faux plus élevé — vérifier tampon au dos impérativement',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.3,
      volume_estime: 1,
    },
    {
      nom: 'Affiche Henryk Tomaszewski — original',
      fabricant: 'Film Polski / théâtres',
      designer: 'Henryk Tomaszewski (1914-2005)',
      categorie: 'AFFICHE',
      epoque: 'années 60-70',
      keywords_trends_fr: 'affiche Tomaszewski école polonaise affiche théâtre',
      dimensions: 'B1 (68x98cm) ou B2 (50x70cm)',
      description: 'Fondateur de l\'école polonaise de l\'affiche. Style dessin libre, calligraphique, très contemporain dans son approche. Ses affiches restent étonnamment modernes 50 ans après. Très prisé des collectionneurs européens.',
      rarete: 'RARE',
      priorite: 'HAUTE',
      prix_achat_min: 25,
      prix_achat_max: 70,
      prix_revente_min: 200,
      prix_revente_max: 700,
      marge_estimee: 1000,
      mots_cles_polonais: 'plakat Tomaszewski · plakat teatralny · plakat filmowy',
      liens_reference: [
        { label: 'Old24 — galerie', url: 'https://www.old24.com' },
        { label: 'LesAffiches.com', url: 'https://lesaffiches.com/index.php/fr/' },
      ],
      tests_authenticite: [
        'Papier épais jauni mat',
        'Format B1 ou B2',
        'Tampon au dos — Tomaszewski a beaucoup travaillé pour les théâtres',
        'Style très reconnaissable — calligraphie et dessin libre',
      ],
      signaux_alerte: [
        'Rare = méfiance accrue — toujours vérifier le tampon au dos',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 0.3,
      volume_estime: 1,
    },
    {
      nom: 'Fotel 366 — Józef Chierowski (1962)',
      fabricant: 'Dolnośląska Fabryka Mebli / Świebodzice (et autres usines)',
      designer: 'Józef Chierowski (1927-2007)',
      categorie: 'FAUTEUIL',
      epoque: '1962-1980',
      keywords_trends_fr: 'fauteuil 366 Chierowski vintage polonais',
      dimensions: 'H: 70cm, L: 62cm, P: 60cm, hauteur assise: 39cm',
      description: 'Icône absolue du design polonais PRL. Dessiné en 1962 après l\'incendie d\'une manufacture de Świebodzice. Produit pendant 20 ans dans des dizaines d\'usines polonaises. Pieds compas en hêtre, accoudoirs courbés, 2 boutons caractéristiques au dossier. Format compact idéal pour petits appartements. Réédité depuis 2014 par 366 Concept — ne pas confondre avec l\'original. REPÉRAGE UNIQUEMENT sur ce voyage — photo + contact vendeur.',
      rarete: 'ABONDANT',
      priorite: 'HAUTE',
      prix_achat_min: 30,
      prix_achat_max: 80,
      prix_revente_min: 350,
      prix_revente_max: 600,
      marge_estimee: 700,
      mots_cles_polonais: 'fotel 366 · fotel Chierowski · fotel PRL · fotel kompas',
      liens_reference: [
        { label: 'Slavia Vintage — original rénové', url: 'https://www.slavia-vintage.com/1-categorie-jouets/875-fauteuil-366-des-annees-60-de-jozef-chierowski-retapisse-bleu-turquoise-pologne' },
        { label: 'Slaviavintage blog — originaux non rénovés', url: 'http://slaviavintage.blogspot.com/2015/05/le-fauteuil-366-de-jozef-chierowski.html' },
        { label: '1stDibs — galerie Chierowski', url: 'https://www.1stdibs.com/fr/creators/jozef-chierowski/furniture/seating/' },
        { label: 'Galerie Parallèle — brut non restauré', url: 'https://www.galerie-parallele.com/fr/archives/64-fauteuil-d-europe-de-l-est-chierowski-modele-366.html' },
        { label: '⚠️ Réédition 366 Concept — à NE PAS confondre', url: 'https://pl.366concept.com/products/fotel-366-w-tkaninie-velvet-bottle-green' },
      ],
      tests_authenticite: [
        'Vis apparentes sur la structure — les rééditions 366 Concept ont des vis cachées',
        'Bois patiné, légèrement usé — bois trop propre et lisse = réédition',
        'Mousse affaissée sur les originaux — rembourrage parfait = réédition',
        'Étiquette usine polonaise sous le siège (nom de fabrique + ville) — étiquette 366 Concept = réédition',
        'Tissu d\'époque usé ou remplacé artisanalement — tissu trop régulier et moderne = réédition',
      ],
      signaux_alerte: [
        'Réédition 366 Concept depuis 2014 : bois trop propre, vis cachées, étiquette 366 Concept',
        'Mousse trop ferme et uniforme = réédition moderne',
        'Prix > 150€ sur le marché = probablement déjà revendu par un intermédiaire',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 12,
      volume_estime: 60,
    },
    {
      nom: 'Fotel 300-190 "Lis" — Rajmund Teofil Hałas',
      fabricant: 'Fabryka Mebli Paczków',
      designer: 'Rajmund Teofil Hałas',
      categorie: 'FAUTEUIL',
      epoque: 'années 60',
      keywords_trends_fr: 'fauteuil renard Halas design polonais vintage',
      dimensions: 'silhouette élancée, pieds fins',
      description: 'Surnommé "Lis" (le renard) pour sa silhouette élancée. Produit à Paczków. Peu connu des vendeurs polonais qui ne savent souvent pas qui est Hałas — excellent arbitrage possible. Très recherché en Europe par les amateurs de design est-européen.',
      rarete: 'RARE',
      priorite: 'HAUTE',
      prix_achat_min: 20,
      prix_achat_max: 50,
      prix_revente_min: 250,
      prix_revente_max: 450,
      marge_estimee: 1000,
      mots_cles_polonais: 'fotel Hałas · fotel 300-190 · fotel PRL Paczków · fotel lis',
      liens_reference: [
        { label: '1stDibs — Rajmund Hałas', url: 'https://www.1stdibs.com/fr/creators/rajmund-halas/furniture/' },
        { label: 'Galerie Parallèle — chaises Hałas', url: 'https://www.galerie-parallele.com/fr/archives' },
      ],
      tests_authenticite: [
        'Étiquette Paczków ou Hałas sous le siège',
        'Pieds fins caractéristiques en hêtre ou bouleau',
        'Silhouette élancée très reconnaissable — le vendeur ne connaît souvent pas l\'artiste',
      ],
      signaux_alerte: [
        'Confusion possible avec d\'autres fauteuils à pieds fins de l\'époque',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 10,
      volume_estime: 50,
    },
    {
      nom: 'Krzesło VAR — Józef Chierowski',
      fabricant: 'Diverses usines polonaises',
      designer: 'Józef Chierowski',
      categorie: 'FAUTEUIL',
      epoque: 'années 60-70',
      keywords_trends_fr: 'chaise contreplaqué vintage design polonais',
      dimensions: null,
      description: 'Chaise légère en contreplaqué moulé avec pieds métal. Souvent vendue en lot de 4 ou 6. Facile à transporter comparé aux fauteuils. Bonne marge si achetée en lot. Même designer que le 366.',
      rarete: 'ABONDANT',
      priorite: 'MOYENNE',
      prix_achat_min: 40,
      prix_achat_max: 80,
      prix_revente_min: 80,
      prix_revente_max: 150,
      marge_estimee: 83,
      mots_cles_polonais: 'krzesło VAR · krzesło Chierowski · krzesła PRL zestaw',
      liens_reference: [],
      tests_authenticite: [
        'Contreplaqué moulé d\'époque — légèrement patiné',
        'Pieds métal tubulaire avec embouts caoutchouc d\'origine',
      ],
      signaux_alerte: [
        'Copies récentes avec contreplaqué trop lisse et brillant',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 3,
      volume_estime: 15,
    },
    {
      nom: 'Fotel coquille "Skorupa" — PRL anonyme',
      fabricant: 'Divers',
      designer: null,
      categorie: 'FAUTEUIL',
      epoque: 'années 60-70',
      keywords_trends_fr: 'fauteuil coquille space age vintage plastique',
      dimensions: null,
      description: 'Fauteuil à coque en fibre de verre ou plastique moulé, design générique PRL des années 60-70. Pas de designer attitré connu. Abondant sur les marchés, peu cher, bonne marge si état correct. Esthétique Space Age très appréciée en France.',
      rarete: 'ABONDANT',
      priorite: 'MOYENNE',
      prix_achat_min: 15,
      prix_achat_max: 40,
      prix_revente_min: 150,
      prix_revente_max: 280,
      marge_estimee: 700,
      mots_cles_polonais: 'fotel muszla · fotel skorupa · fotel PRL plastik · fotel space age',
      liens_reference: [],
      tests_authenticite: [
        'Fibre de verre ou plastique épais d\'époque — pas de plastique fin moderne',
        'Structure métallique tubulaire soudée d\'époque',
        'Traces d\'usure cohérentes avec l\'âge',
      ],
      signaux_alerte: [
        'Reproductions modernes en plastique fin — trop légères, trop lisses',
        'Fissures dans la coque = coût de restauration à déduire',
      ],
      statut: 'A_CHERCHER',
      poids_estime: 6,
      volume_estime: 40,
    },
  ]

  for (const obj of objets) {
    await prisma.objet.create({ data: obj })
  }
  console.log(`${objets.length} objets créés`)

  // Checklist
  const checklistItems = [
    'Réserver vol Ryanair Beauvais → Modlin',
    'Vérifier dates ZOO Market sur Facebook',
    'Retirer cash (800-1000 PLN au kantor sur place)',
    'Charger Google Translate polonais en mode offline',
    'Télécharger app Jakdojade (transports Varsovie)',
    'Installer Uber / Bolt',
    'Scanner OLX Polska avant départ (filtre Warszawa)',
    'Acheter supplément bagage soute Ryanair 20kg',
    'Préparer sac souple pliable (type Frakta IKEA)',
    'Prendre batterie externe',
    'Prendre carnet + stylo',
  ]

  for (let i = 0; i < checklistItems.length; i++) {
    await prisma.checklistItem.create({ data: { label: checklistItems[i], ordre: i + 1 } })
  }
  console.log(`${checklistItems.length} items checklist créés`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
